version: "3.8"
services:
  service:
    build: .
    container_name: service
    restart: unless-stopped
    networks:
      - service-network
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - service
    networks:
      - service-network
  certbot:
  image: certbot/certbot
  container_name: certbot
  volumes:
    - certbot-etc:/etc/letsencrypt
    - certbot-var:/var/lib/letsencrypt
    - web-root:/var/www/html
  depends_on:
    - webserver
  command: certonly --webroot --webroot-path=/var/www/html --email dvn281002@gmail.com --agree-tos --no-eff-email --staging -d kmas-api.nnee.dev
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local

networks:
  service-network:
    driver: bridge
