version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build-push:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION
          registry-id: AWS_REGISTRY_ID
          repo: $AWS_REPO_NAME
  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $AWS_EC2_FINGERPRINTS
      - run: ssh $AWS_EC2_USER@$AWS_EC2_IP cd kmas-service && aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com && docker-compose down && docker-compose pull && docker-compose up -d

workflows:
  kmas-service:
    jobs:
      - build-push
      - deploy:
          requires:
            - build-push
