version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION
          registry-id: AWS_REGISTRY_ID
          repo: $AWS_REPO_NAME
  deploy:
    jobs:
      requires:
        - build_and_push_image
      steps:
         - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
        - run:
          name: The Second Step
          command: echo 'test test'
