version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Building"
  deploy:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Deploying"

workflows:
  kmas-service:
    jobs:
      - build
      - deploy
