version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build-push:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION
          registry-id: AWS_REGISTRY_ID
          repo: $AWS_REPO_NAME
  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $VPS_FINGERPRINTS
      - run: ssh $VPS_USER@$VPS_IP cd kmas-service && deploy.sh

workflows:
  kmas-service:
    jobs:
      - build-push
      - deploy:
          requires:
            - build-push
