version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build-push:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION
          registry-id: AWS_REGISTRY_ID
          repo: $AWS_REPO_NAME
  deploy:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 37:71:71:a7:be:4f:9b:01:9f:b7:9d:08:eb:fb:ae:04
      - run: ssh $VPS_USER@$VPS_IP deploy.sh

workflows:
  kmas-service:
    jobs:
      - build-push
      - deploy:
          requires:
            - build-push
