const HTTP_OK = 200,
  HTTP_UNAUTHORIZED = 401,
  HTTP_INTERNAL_SERVER_ERROR = 500,
  HTTP_SERVICE_UNAVAILABLE = 503,
  HOST_KMA = "http://qldt.actvn.edu.vn/CMCSoft.IU.Web.info",
  HOST = "https://kmas.nnee.me"

export {
  HTTP_OK,
  HTTP_UNAUTHORIZED,
  HTTP_INTERNAL_SERVER_ERROR,
  HTTP_SERVICE_UNAVAILABLE,
  HOST_KMA,
  HOST,
}
