name: Deploy

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build . -t kmas-api
          docker save -o kmas-api.tar kmas-api
          zip kmas-api.zip kmas-api.tar
      - uses: actions/upload-artifact@v3
        with:
          name: kmas-api
          path: kmas-api.zip
  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: kmas-api
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "kmas-api.zip,.prod.env,docker-compose.yml"
          target: "kmas-api"
      - uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /kmas-api
            unzip kmas-api.zip
            docker load -i kmas-api.tar
            docker compose down
            docker compose up -d
            rm kmas-api.*
            exit
