name: Deploy

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build . -t kmas-api
          docker save -o ./kmas-api-image.tar kmas-api
          zip /kmas-api-image.zip /kmas-api-image.tar
      - uses: actions/upload-artifact@v3
        with:
          name: kmas-api-image
          path: kmas-api-image.zip
  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: kmas-api-image
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "kmas-api-image.zip,.env.prod"
          target: "/kmas-api"
#       - uses: appleboy/ssh-action@v0.1.8
#         with:
#           host: ${{ secrets.VM_IP }}
#           username: ${{ secrets.VM_USERNAME }}
#           key: ${{ secrets.VM_SSH_KEY }}
#           script: |
#             cd /kmas-api
#             echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
#             docker compose down
#             docker compose up -d
