name: Docker Image CI

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the Docker image

    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build . -t nnee2810/kmas-api
          echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          docker push nnee2810/kmas-api
